[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200

[[redirects]]
  from = "/*.js"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*.css"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*.png"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*.jpg"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*.jpeg"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*.gif"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*.svg"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*.ico"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*.woff"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*.woff2"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*.ttf"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*.eot"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*.json"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*.webp"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*.wav"
  to = "/:splat"
  status = 200

# SPA routing - must be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 